
name: Writing GitHub Metrics Files and Googlesheet
on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  write-data:
    name: Write Data
    runs-on: ubuntu-latest
    container:
      image: cansav09/metricminer

    steps:
      - name: Authorize metricminer
        env:
          METRICMINER_CALENDLY: ${{ secrets.METRICMINER_CALENDLY }}
          METRICMINER_GITHUB_PAT: ${{ secrets.METRICMINER_GITHUB_PAT }}
          METRICMINER_GOOGLE_ACCESS: ${{ secrets.METRICMINER_GOOGLE_ACCESS }}
          METRICMINER_GOOGLE_REFRESH: ${{ secrets.METRICMINER_GOOGLE_REFRESH }}
        run: Rscript -e ".github/worfklows/get_itn_data.R"
